### ISSUE TITLE
Unable to compile as is

### ISSUE THREAD

**Issue by anubister** [BGR360/GirinoDuo#1]
Hello,
when trying to compile/transfer to my Arduino Uno (env arduino 1.8.1), 

- I first get : 

```
In file included from /home/anubis/GirinoDuo/GirinoDuo.ino:25:0:
Girino.h:57: error: invalid preprocessing directive #elseif
 #elseif defined(MEGA_32U4)
```

==> to correct elseif by elif

- Then : 
```
/home/anubis/GirinoDuo/GirinoDuo.ino: In function 'void loop()':
GirinoDuo:100: error: 'sendWaveform' was not declared in this scope
     sendWaveform();
```

==> it looks like Interface.h and Settings.h are missing

Then I'm able to compile & transfer.
I'm not yet able to connect with [Girinoscope](https://github.com/Chatanga/Girinoscope), but that's another topic.

**Comment by BGR360** [comment]
Hi, I'm sorry anubister, but I have actually abandoned this project.
